# Generated by Django 3.1.7 on 2021-04-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210425_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
