# Generated by Django 3.1.7 on 2021-04-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210429_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
    ]
